name: CI checks

on:
  push:
    branches: [ staging, production, dx ]
  pull_request:
    branches: [ staging, production ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy pyparsing
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Type checking using mypy
      run: |
        mypy -p acbs
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --exclude='build,.mypy_cache,venv,dist' --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --exclude='build,.mypy_cache,venv,dist' --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run unittests
      run: ARCH=amd64 python -m unittest discover ./tests/
    - name: Install native dependencies
      run: sudo apt-get update && sudo apt-get install -y libapt-pkg-dev
    - name: Test building
      run: python setup.py build -f
